# Generated by Django 4.0.4 on 2022-06-02 04:42

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchKeywordLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_date', models.DateTimeField(default=datetime.datetime(2022, 6, 2, 4, 42, 49, 402195, tzinfo=utc))),
                ('keyword_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.searchurlkeyword')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.userprofile')),
            ],
        ),
    ]
