# Generated by Django 4.0.4 on 2022-06-02 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_searchkeywordlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchkeywordlog',
            name='search_date',
            field=models.DateTimeField(),
        ),
    ]
